rijcir/urls.py
from django.contrib import admin
from django.urls import path
from fundacion.views import home,registro,nosotros,date

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",home, name=''),
    path("registro/",registro, name='registro'),
    path("nosotros/",nosotros, name='nosotros'),
    path("date/",date, name='date'),
]

fundacion/models.py
from django.db import models
from django.core.validators import MinLengthValidator

iglesias = (("CATOLICA","Católica"),("ADVENTISTA","Adventista"),("EVANGELICA","Evangélica"),("TESTIGO DE JEHOVA","Testigo de Jehova"),
            ("MORMONA","Mormona"),("UNIVERSAL","Universal"),("CRISTIANA","Cristiana"),("OTRA","Otra"))

sexo = (("M","Masculino"),("F","Femenino"))

grado = (("PRIMARIO","Primario"),("SECUNDARIO","Secundario"),("UNIVERSITARIO","Universitario"))

paises = (("ARGENTINA","Argentina"),("BOLIVIA","Bolivia"),("BRASIL","Brasil"),("COLOMBIA","Colombia"),("COSTA RICA","Costa Rica"),("CUBA","Cuba"),
          ("CHILE","Chile"),("ECUADOR","Ecuador"),("EL SALVADOR","El Salvador"),("GUATEMALA","Guatemala"),
         ( "HONDURAS","Honduras"),("MEXICO","México"),("NICARAGUA","Nicaragua"),("PANAMA","Panamá"),("PARAGUAY","Paraguay"),("PERU","Perú"),
         ("REPUBLICA DOMINICANA","República Dominicana"),("URUGUAY","Uruguay"),("VENEZUELA","Venezuela"))


class datos(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    cedula = models.CharField(max_length=11, validators=[MinLengthValidator(11)])
    telefono = models.CharField(max_length=10 ,validators=[MinLengthValidator(10)])
    grado_academico = models.CharField(max_length=100, choices=grado)
    ocupacion = models.CharField(max_length=100)
    sexo = models.CharField(max_length=100, choices=sexo, default="Masculino")
    denominacion = models.CharField(max_length=100, choices=iglesias)
    fecha_nacimiento = models.DateField()
    pais = models.CharField(max_length=100, choices=paises, default="REPUBLICA DOMINICANA") 
    provincia = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    email = models.EmailField()
   

fundacion/forms.py
from django import forms
from .models import datos



class datosForm(forms.ModelForm):
    
    class Meta:
        model = datos
        fields = '__all__'
      
          
        

fundacion/views.py
from django.shortcuts import render
from .forms import datosForm
from django.shortcuts import redirect
from fundacion.models import datos

def home(request):
    datoss= datos.objects.all()
    return render(request, "home.html", {"datoss":datoss})  

def registro(request):
     if request.method == 'POST': 
        form = datosForm(request.POST)
     
        if form.is_valid():
         form.save()
         return redirect("/")
     
     else: form = datosForm() 
     context = {'form': form}   
     return render(request, "register.html", context)
   

def nosotros(request):
    return render(request, "nosotros.html")

def date(request):
    return render(request, "index.html")   

fundacion/templates/home.html
{% extends 'layout.html' %} 
{% load static %}

{% block slide %}

<header>
   
    <!-- Background image -->
    <div class="relative overflow-hidden bg-no-repeat bg-cover" style="
      background-position: 50%;
      background-image: url('https://mdbcdn.b-cdn.net/img/new/slides/146.webp');
      height: 350px;
    ">
      <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed"
        style="background-color: rgba(0, 0, 0, 0.75)">
        <div class="flex justify-center items-center h-full">
          <div class="text-center text-white px-6 md:px-12">
            <h1 class="text-5xl font-bold mt-0 mb-6">Red Interdenominacional</h1>
            <h3 class="text-4xl font-bold mb-8">de Jovenes Cristianos</h3>
            <a href="{% url 'registro' %}" type="button"
              class="inline-block px-6 py-2.5 border-2 border-white text-white font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
              data-mdb-ripple="true" data-mdb-ripple-color="light">
              ¡Inscribete!
          </a>
          </div>
        </div>
      </div>
    </div>
    <!-- Background image -->
  </header>

{% endblock %}

{% block home %}

<section class="text-gray-600 body-font bg-[#F4F3FA] h-screen">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap -m-4 text-center">

        <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Catolica</h2>
                <h3 id="catolica" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/catolica2.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

        <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Adventista</h2>
                <h3 id="adventista" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/adventista.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Evangelica</h2>
                <h3 id="evangelica" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/evangelica.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Testigo de Jehova</h2>
                <h3 id="testigo" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/testigos.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Mormones</h2>
                <h3  id="mormones" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/mormones.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Universal</h2>
                <h3 id="universal" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/universal.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Cristiana</h2>
                <h3 id="cristiana" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/cristiana.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Otra</h2>
                <h3 id="otra" class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/otras.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Iglesia</h2>
                <h3 class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/catolica2.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Iglesia</h2>
                <h3 class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/catolica2.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Iglesia</h2>
                <h3 class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/catolica2.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

          <div class="p-4 sm:w-1/2 lg:w-1/6 w-full ">
            <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
              <div>
                <h2 class="text-gray-900 text-lg font-bold">Iglesia</h2>
                <h3 class="mt-2 text-xl font-bold text-green-500 text-left"></h3>
              </div>
              <div
                class="bg-gradient-to-tr from-white-600 to-indigo-600 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
                <div>
                  <img src="{% static "img/catolica2.png" %}" alt="Portada" width="150px" height="150px">  
                </div>
              </div>
            </div>
          </div>

        
    
      </div>
    </div>
</section>

<script>
  let catolica = 0;
  let adventista = 0;
  let evangelica = 0;
  let testigo = 0;
  let mormona = 0;
  let universal = 0;
  let cristiana = 0;
  let otra = 0;
</script>
{% for datos in datoss %}
{% if datos.denominacion == "CATOLICA" %}
<script>
  catolica = catolica + 1; 
  document.getElementById('catolica').innerHTML = catolica;
</script>
{% endif %}

{% if datos.denominacion == "ADVENTISTA" %}
<script>
  adventista = adventista + 1; 
  document.getElementById('adventista').innerHTML = adventista;
</script>
{% endif %}

{% if datos.denominacion == "EVANGELICA" %}
<script>
  evangelica = evangelica + 1; 
  document.getElementById('evangelica').innerHTML = evangelica;
</script>
{% endif %}

{% if datos.denominacion == "TESTIGO DE JEHOVA" %}
<script>
  testigo = testigo + 1; 
  document.getElementById('testigo').innerHTML = testigo;
</script>
{% endif %}

{% if datos.denominacion == "MORMONA" %}
<script>
  mormona = mormona + 1; 
  document.getElementById('mormona').innerHTML = mormona;
</script>
{% endif %}

{% if datos.denominacion == "UNIVERSAL" %}
<script>
  universal = universal + 1; 
  document.getElementById('universal').innerHTML = universal;
</script>
{% endif %}

{% if datos.denominacion == "CRISTIANA" %}
<script>
  cristiana = cristiana + 1; 
  document.getElementById('cristiana').innerHTML = cristiana;
</script>
{% endif %}

{% if datos.denominacion == "OTRA" %}
<script>
  otra = otra + 1; 
  document.getElementById('otra').innerHTML = otra;
</script>
{% endif %}

{% if datos.denominacion == "CATOLICA" %}
<script>
  catolica = catolica + 1; 
  document.getElementById('catolica').innerHTML = catolica;
</script>
{% endif %}








{% endfor %}


{% endblock %}

fundacion/templates/nosotros.html
{% extends 'layout.html' %}
{% load static %}

{% block nosotros %}

<div class="about-section">
    <h1>About Us Page</h1>
    <p>Some text about who we are and what we do.</p>
    <p>Resize the browser window to see that this page is responsive by the way.</p>
  </div>
  
  <h2 style="text-align:center">Our Team</h2>
  <div class="row">
    <div class="column">
      <div class="card">
        <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">
        <div class="container">
          <h2>Jane Doe</h2>
          <p class="title">CEO & Founder</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>jane@example.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/w3images/team2.jpg" alt="Mike" style="width:100%">
        <div class="container">
          <h2>Mike Ross</h2>
          <p class="title">Art Director</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>mike@example.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  
    <div class="column">
      <div class="card">
        <img src="/w3images/team3.jpg" alt="John" style="width:100%">
        <div class="container">
          <h2>John Doe</h2>
          <p class="title">Designer</p>
          <p>Some text that describes me lorem ipsum ipsum lorem.</p>
          <p>john@example.com</p>
          <p><button class="button">Contact</button></p>
        </div>
      </div>
    </div>
  </div>

<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
      }
      
      html {
        box-sizing: border-box;
      }
      
      *, *:before, *:after {
        box-sizing: inherit;
      }
      
      .column {
        float: left;
        width: 33.3%;
        margin-bottom: 16px;
        padding: 0 8px;
      }
      
      .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: 8px;
      }
      
      .about-section {
        padding: 50px;
        text-align: center;
        background-color: #474e5d;
        color: white;
      }
      
      .container {
        padding: 0 16px;
      }
      
      .container::after, .row::after {
        content: "";
        clear: both;
        display: table;
      }
      
      .title {
        color: grey;
      }
      
      .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
      }
      
      .button:hover {
        background-color: #555;
      }
      
      @media screen and (max-width: 650px) {
        .column {
          width: 100%;
          display: block;
        }
      }
</style>

{% endblock %}

fundacion/templates/register.html
{% extends 'layout.html' %} 
{% load static %}
{% block registro %}

<script src="https://momentjs.com/downloads/moment.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<div class="container">
   
    <form method="POST" class="form-horizontal" role="form" style="margin-top:30px;">
        {% csrf_token %}
     <h2>Registrate</h2>  
    <div class="form-group">
    <label for="id_nombre" class="col-sm-3 control-label">Nombre:</label>
    <div class="col-sm-9">
          <input type="text" name="nombre" maxlength="100" required="" id="id_nombre" placeholder="Nombre" class="form-control" autofocus> 
    </div>
    </div>

  
    <div class="form-group">
    <label for="id_apellido" class="col-sm-3 control-label">Apellido:</label>
    <div class="col-sm-9">
    <input type="text" name="apellido" maxlength="100" required="" id="id_apellido" placeholder="Apellido" class="form-control" autofocus>
    </div>
    </div>

  
  <div class="form-group">
    <label for="id_cedula" class="col-sm-3 control-label">Cedula:</label>
    <div class="col-sm-9">
    <input type="text" name="cedula" maxlength="11" required="" id="id_cedula" placeholder="Cédula" class="form-control" autofocus>
    
</div>
</div>

  
<div class="form-group">
    <label for="id_telefono" class="col-sm-3 control-label">Telefono:</label>
    <div class="col-sm-9">
    <input type="text" name="telefono" maxlength="10" required="" id="id_telefono" placeholder="Telefono" class="form-control" autofocus>
</div>
</div>

  
<div class="form-group">
    <label for="id_grado_academico"  class="col-sm-3 control-label">Grado academico:</label>
    <div class="col-sm-9">
    <select name="grado_academico" required="" id="id_grado_academico"  class="form-control" autofocus style="height:33px;">
  <option value="" selected="">---------</option>

  <option value="PRIMARIO">Primario</option>

  <option value="SECUNDARIO">Secundario</option>

  <option value="UNIVERSITARIO">Universitario</option>

</select>
</div>
</div>

  
<div class="form-group">
    <label for="id_ocupacion"  class="col-sm-3 control-label">Ocupacion:</label>
    <div class="col-sm-9">
    <input type="text" name="ocupacion" maxlength="100" required="" id="id_ocupacion" placeholder="Ocupacion" class="form-control" autofocus>
</div>
</div>

  
  <div class="form-group">
    <label for="id_sexo"  class="col-sm-3 control-label">Sexo:</label>
    <div class="col-sm-9">
    <select name="sexo" id="id_sexo"  class="form-control" autofocus style="height:33px;">
  <option value="M">Masculino</option>

  <option value="F">Femenino</option>

</select>
</div>
</div>

  
  <div class="form-group">
    <label for="id_denominacion"  class="col-sm-3 control-label">Denominacion:</label>
    <div class="col-sm-9">
    <select name="denominacion" required="" id="id_denominacion"  class="form-control" autofocus style="height:33px;">
  <option value="" selected="">---------</option>

  <option value="CATOLICA">Católica</option>

  <option value="ADVENTISTA">Adventista</option>

  <option value="EVANGELICA">Evangélica</option>

  <option value="TESTIGO DE JEHOVA">Testigo de Jehova</option>

  <option value="MORMONA">Mormona</option>

  <option value="UNIVERSAL">Universal</option>

  <option value="CRISTIANA">Cristiana</option>

  <option value="OTRA">Otra</option>

</select>
</div>
</div>

  
  <div class="form-group">
    <label for="id_fecha_nacimiento"  class="col-sm-3 control-label">Fecha nacimiento:</label>
    <div class="col-sm-9">
    <label class="real">   
    <input type="text" name="fecha_nacimiento" required="" id="id_fecha_nacimiento" placeholder="fecha de nacimiento" class="form-control" autofocus style="width:367px;">
    </label>
</div>
</div>

  
  <div class="form-group">
    <label for="id_pais"  class="col-sm-3 control-label">Pais:</label>
    <div class="col-sm-9">
    <select name="pais" id="id_pais"  class="form-control" autofocus style="height:33px;">
  <option value="ARGENTINA">Argentina</option>

  <option value="BOLIVIA">Bolivia</option>

  <option value="BRASIL">Brasil</option>

  <option value="COLOMBIA">Colombia</option>

  <option value="COSTA RICA">Costa Rica</option>

  <option value="CUBA">Cuba</option>

  <option value="CHILE">Chile</option>

  <option value="ECUADOR">Ecuador</option>

  <option value="EL SALVADOR">El Salvador</option>

  <option value="GUATEMALA">Guatemala</option>

  <option value="HONDURAS">Honduras</option>

  <option value="MEXICO">México</option>

  <option value="NICARAGUA">Nicaragua</option>

  <option value="PANAMA">Panamá</option>

  <option value="PARAGUAY">Paraguay</option>

  <option value="PERU">Perú</option>

  <option value="REPUBLICA DOMINICANA" selected="">República Dominicana</option>

  <option value="URUGUAY">Uruguay</option>

  <option value="VENEZUELA">Venezuela</option>

</select>
</div>
</div>

  
  <div class="form-group">
    <label for="id_provincia"  class="col-sm-3 control-label">Provincia:</label>
    <div class="col-sm-9">
    <input type="text" name="provincia" maxlength="100" required="" id="id_provincia" placeholder="Provincia" class="form-control" autofocus>
</div>
</div>

  
  <div class="form-group">
    <label for="id_sector"  class="col-sm-3 control-label">Sector:</label>
    <div class="col-sm-9">
    <input type="text" name="sector" maxlength="100" required="" id="id_sector" placeholder="Sector" class="form-control" autofocus>
</div>
</div>

  
  <div class="form-group">
    <label for="id_email"  class="col-sm-3 control-label">Email:</label>
    <div class="col-sm-9">
    <input type="email" name="email" maxlength="254" required="" id="id_email" placeholder="Email" class="form-control" autofocus>
</div>
</div>


         <input type="submit" value="Guardar" class="btn btn-primary" name="_save"> 
    </form>

</div>

<style>
          body {
            background: url('https://static-communitytable.parade.com/wp-content/uploads/2014/03/rethink-target-heart-rate-number-ftr.jpg') fixed;
           background-size: cover;
       }
       
       *[role="form"] {
           max-width: 530px;
           padding: 15px;
           margin: 0 auto;
           border-radius: 0.3em;
           background-color: #f2f2f2;
       }
       
       *[role="form"] h2 { 
           font-family: 'Open Sans' , sans-serif;
           font-size: 40px;
           font-weight: 600;
           color: #000000;
           margin-top: 5%;
           text-align: center;
           text-transform: uppercase;
           letter-spacing: 4px;
       }
       
       
 </style>

{% endblock %}